### ISSUE TITLE
Expose function to process text without requiring DOM element

### ISSUE THREAD

**Issue by sergeyt** [ritz078/embed.js#110]
Is it easy to implement function `string -> string` in this package to convert text without requiring DOM element?

**Comment by ritz078** [comment]
Yes it is.

```js
var x = new EmbedJS([options], [optional input string])

//Get the resulting string
  x.text(function(data){
    console.log(data); //The resultant string
  })
```

In this case you don't need to pass the `element` key in `options` object.

**Comment by sergeyt** [comment]
@ritz078 great, thank you for answer. I'll try to use this code path in my [markdown](https://github.com/reactbits/markdown) component until I'll find a time to write own code with smaller size. BTW I think you could significantly optimize this library for example using [hashtrie](https://github.com/mattbierner/hashtrie) to quickly lookup embed modules by hostname and then filter by regex to find exact module.

**Comment by ritz078** [comment]
Hi @sergeyt ,

I am very much open to ideas regarding the optimisation of this plugin and its on high priority. v4 is under developement and i would really open to suggestions and contribution. Thanks.

**Comment by Yamakaky** [comment]
How would you integrate your package in a react app?

**Comment by ritz078** [comment]
You can pass the string and get the resulting string from this plugin and use in React app but there will be few problems on click events. Some features like github gist ebedding, click on youtube and vimeo videos are still dependent on presence of DOMelements.  I will break them into separate smaller method that can be called after the instance has been initialized. All these features will be available in v4. I may also create a react component based on this plugin so that it is easier to use with React.
