### ISSUE TITLE
new update: missing options?

### ISSUE THREAD

**Issue by comtronix** [ritz078/embed.js#14]
In the previous versios there where some other options, in the latest they are gone..
Did i miss something?

                  codepenEmbed      :true,
                  codepenHeight     :300,
                  jsfiddleEmbed     :true,
                  jsfiddleHeight    :300,
                  jsbinEmbed        :true,
                  jsbinHeight       :300,
                  ideoneEmbed       :true,
                  ideoneHeight      :300,
                  plunkerEmbed      :true,
                  plunkerHeight     :300,

                  twitchtvEmbed     :true,
                  dotsubEmbed       :true,
                  dailymotionEmbed  :true,
                  vineEmbed        : true,

                  tedEmbed         :true,
                  liveleakEmbed     :true,

**Comment by ritz078** [comment]
Yes this method of taking options was not nice as with every added service this would have got longer. So I have introduced a new options format instead of all the above
```javascript
//An array of services excluded from embedding...
//Options:codePen/jdFiddle/jsBin/ideone/plunker/soundcloud/twitchTv/dotSub/dailymotion/vine/ted/liveleak/spotify
 //Can exclude all options by setting it to 'all'
excludeEmbed     :['twitchTv'],
//Height of jsfiddle/codepen/jsbin/ideone/plunker
codeEmbedHeight  :300,
```
I guess its easy to understand about how this works. Now I can add any new service without making the options documentation longer. Just add the service in the array which you want to exclude.

**Comment by comtronix** [comment]
Thanx for the information, it's clear now :)
