### ISSUE TITLE
build.json missing ?

### ISSUE THREAD

**Issue by quasiperfect** [ritz078/embed.js#150]
hi

thanks for your work

for a custom build you say "Set the features you don't want to false in build.json" 
i don't see any build.json or i'm missing something ?

**Comment by ritz078** [comment]
Hi @quasiperfect ,

I have updated the Readme. Custom build option was present in v3 . In the current version, it has been removed as it broke some functionalities. V4 is already ~50KB less in size than V3 so I don't think you would need that. Removing a functionality changed the size by around 1 or 2 KB. So I felt it was better to optimize the whole library instead of providing that option. 

I would definitely like to bring it back once I figure out a way in which it doesn't break the other functionalities.

**Comment by quasiperfect** [comment]
@ritz078 thanks for you fast replay
i wasn't worried about the size only performance 
i will set to false the parser options i don't use (twitter etc)

**Comment by ritz078** [comment]
That should solve it for you. Performance wise v4 is lot better.
