### ISSUE TITLE
URLs parsing without 'http(s)'

### ISSUE THREAD

**Issue by Yonirt** [ritz078/embed.js#193]
Hello @ritz078,

Why is not possible to linkify a url without http(s) protocol and only in the format like 'www.example.com'?

Thank you!

**Comment by SnehaMidha** [comment]
@ritz078 Changing return expression of toURL from `(string.indexOf('//') === -1) ? ('//' + string) : string` to `(string.indexOf('http') ===-1)?('http://'+string):string` works well for flicker and instagram

and removal of `https?:\/\/(?:[0-9A-Z-]+\.)?` from regex.youtube works well for youtube

**Comment by ritz078** [comment]
@SnehaMidha You have misunderstood the issue. The issue is only for normal urls where `https://x.com` is converted to URL but `www.x.com` is not converted to a url as the regex [here](https://github.com/ritz078/embed.js/blob/c60b1693225bf72d6fa01625aa3fe28b181888b9/src/js/modules/utils.js#L134) doesn't identify the later as a valid URL. This has nothing to with services like  instagram, youtube etc.

**Comment by ishakalra** [comment]
@ritz078 In the urlRegex function, the beginning says : (\b(https?|ftp|file):\/\/[^,.\s]+[^\s]*[^,.\s]+)|(?:https?:\/\/). So is it essentially looking for a URL which goes like https://https:// or ftp://https:// ? If this is the case, could you give us an example?

**Comment by ritz078** [comment]
@ishakalra Hopefully this helps https://regex101.com/r/FkMl7i/1

**Comment by sohamidha** [comment]
@ritz078 Please check this link https://regex101.com/r/FkMl7i/2
This accepts www.github.com and others as well.

**Comment by ritz078** [comment]
@sohamidha seems great. You can create a PR.

**Comment by ritz078** [comment]
guys please don't make it a race to open a PR. Its tough for me 😄 . Try to open PRs for other issues. I understand this was the easiest one but I can help you for other issues too.
