### ISSUE TITLE
Google dev key

### ISSUE THREAD

**Issue by jesusprubio** [ritz078/embed.js#37]
Hi, could you please show how create the Google keys? I only can get it working using the ones included in the demo. With mines I only get a forbidden message.

Thanks in advance :)

**Comment by comtronix** [comment]
Go to the Google Developers Console.

Select a project, or create a new one.

In the sidebar on the left, expand APIs & auth. Next, click APIs. In the list of APIs, make sure all of the APIs you are using show a status of ON. In the sidebar on the left, select Credentials.

Click Create new Key and select the appropriate key type:

Create and use a server key if your application runs on a server. Do not use this key outside of your server code. For example, do not embed it in a web page. To prevent quota theft, restrict your key so that requests are only allowed from your servers' source IP addresses.

OR

Create and use a browser key if your application runs on a client, such as a web browser. To prevent your key from being used on unauthorized sites, only allow referrals from domains you administer.

**Comment by jesusprubio** [comment]
Thanks, I had a problem with the domain/ip :)

**Comment by comtronix** [comment]
Yw!
