### ISSUE TITLE
Support for random url embedding

### ISSUE THREAD

**Issue by mastersilv3r** [ritz078/embed.js#94]
Like facebook extracts title, preview image and description of a web page, can that be added to embed.js as well? 

If not, can you point to a repo which can be used for the same? Can add that to embed.js and happy to send you a pull request.

**Comment by ritz078** [comment]
Hi @mastersilv3r ,

There are limitations to it due to cross domain restrictions. You need to have your own server to crawl and save their data. You can create your own server and use this service with embed.js. I have just added this feature a few days ago. Docs are still not updated.

```javascript
 openGraphEndpoint : 'https://opengraph.io/api/1.0/site/${url}',
 onOpenGraphFetch:function(data){
	data.hybridGraph.success = data.error ?  false : true;
	return data.hybridGraph;
}
```

You can see a demo [here](http://codepen.io/ritz078/pen/ZQeaaG). You can see the discussion [here](https://github.com/ritz078/embed.js/issues/82)

**Comment by mastersilv3r** [comment]
Thanks ritesh. Also for the awesome library.
